<div class="header-spacer"></div>
<div class="container">
    <div class="text-block large-paragraph">
        <h1>About</h1>
        <p>Tethered Publics began with a question; how can we bring community, art and the digital together? Currently based in South London, we were looking for a way to give contemporary artists the opportunity to produce work with a focus on the cultural narratives of their own environment, and in turn, create a platform for people to discover their work.</p>
        <p>What emerged is a hybrid digital experience in which artists are given the opportunity to experiment with new technologies while producing location based digital art for people to discover through an IOS app. Allowing both artists and the public to explore and rediscover their environment through a new lens.</p>
        <p>Tethered Publics does what it says on the tin, tethering artworks to locations and allowing the public to view site-specific art through a simple and user-friendly app. Making use of geolocation technology, an integrated map allows app users to discover artworks, or simply be notified when work is close by. Allowing people to curate their own art trail, or simply view exciting works along their regular journeys.</p>
        <p>Tethered Publics is a locally digital project focused on creativity and collaboration. It aims to expand access and assist artists by giving them a platform and the support they need to be innovative, experimental and reflective. Our team, a small group of artists and developers, volunteer their time to create a friendly and supportive space, that allows artists to realise ideas that may be technologically out of reach.</p>
        <p>The project runs on the ethos that, in the contemporary world, both art and technology demand collaboration. The grand aim of this project is to create an expansive network with creativity and skill-sharing at its core. If you are interested in collaborating, or are keen to know more, get in touch.</p>
    </div>
</div>